#include "RADAR_TargetScatterLocation.h"

#include <fstream>
#include <sstream>
#include <iostream>
#include <vector>

const double RADAR_TargetScatterLocation::kPi = 3.1415926535897932384626433832795;
const double RADAR_TargetScatterLocation::kDegToRad = RADAR_TargetScatterLocation::kPi / 180.0;

// 与已经对齐的 RADAR_Platform 保持一致的椭球和自转常量。
const double RADAR_TargetScatterLocation::kEarthSemiMajorAxis = 6378137.0;
const double RADAR_TargetScatterLocation::kEarthSemiMinorAxis = 6356752.0;
const double RADAR_TargetScatterLocation::kEarthRotationRate = 7.2921151467e-5;

#ifndef SV_CODE_GEN
DEFINE_MODEL_INTERFACE(RADAR_TargetScatterLocation)
{
	SET_MODEL_DESCRIPTION("Target Scatter Location");
	SET_MODEL_CATEGORY("Radar");

	// --------- 输入端口 ---------
	// 按帮助文档端口号：Port 1=Roll, Port 2=Pitch, Port 3=Yaw。
	{
		auto p = ADD_MODEL_INPUT(Roll);
		p.SetDescription("The roll angle of target body frame (deg)");
		p.SetOptional(true);
	}
	{
		auto p = ADD_MODEL_INPUT(Pitch);
		p.SetDescription("The pitch angle of target body frame (deg)");
		p.SetOptional(true);
	}
	{
		auto p = ADD_MODEL_INPUT(Yaw);
		p.SetDescription("The yaw angle of target body frame (deg)");
		p.SetOptional(true);
	}

	// --------- 输出端口 ---------
	// 按帮助文档端口号：Port 4=Pos, Port 5=ScatterRCS。
	{
		auto p = ADD_MODEL_OUTPUT(Pos);
		p.SetDescription("Target position value in ECI frame");
	}
	{
		auto p = ADD_MODEL_OUTPUT(ScatterRCS);
		p.SetDescription("The RCS values of target scatters");
	}

	// --------- Trajectory_Mode ---------
	{
		auto p = ADD_MODEL_ENUM_PARAM(Trajectory_Mode, Trajectory_ModeEnum);
		p.AddEnumeration("ECI_Frame", RADAR_TargetScatterLocation::ECI_Frame);
		p.AddEnumeration("UserDefined", RADAR_TargetScatterLocation::User_Defined);
		p.AddEnumeration("SimpleXYZ_Frame", RADAR_TargetScatterLocation::SimpleXYZ_Frame);
		p.SetDefaultValue("ECI_Frame");
		p.SetDescription("The mode of trajectory generation: ECI_Frame: the output in the ECI frame is generated in this model; UserDefined: Users can import the file which trajectory in ECI frame is generated by users; SimpleXYZ_Frame: the output under Cartesian coordinate is generated in this model: ECI_Frame, UserDefined, SimpleXYZ_Frame");
	}

	// --------- User Defined 参数 ---------
	{
		SystemVueModelBuilder::DFParam p = ADD_MODEL_PARAM(FileName);
		p.SetDefaultValue("");
		p.SetDescription("The target scatters location file path. The each line format in the file is x0 y0 z0 rcs0");
		p.SetParamAsFile();
		p.SetHideCondition("Trajectory_Mode ~= 1");
	}

	// --------- 公共参数 ---------
	{
		auto p = ADD_MODEL_PARAM(NumberOfTargetScatter);
		p.SetDefaultValue("1");
		p.SetDescription("The number of target scatters");
	}

	// --------- ECI_Frame / SimpleXYZ_Frame 参数 ---------
	{
		auto p = ADD_MODEL_ARRAY_PARAM(ScatterLoc, ScatterLocSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetUnit(SystemVueModelBuilder::Units::LENGTH);
		p.SetDescription("The scatter locations and the object centroid is the reference point");
		p.SetHideCondition("Trajectory_Mode == 1");
	}

	// --------- ECI_Frame 参数 ---------
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Position_Initial, Position_InitialSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The target initial position which is defined in the LLAFrame. [longitude(deg), latitude(deg), height(m)]");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}
	{
		auto p = ADD_MODEL_PARAM(Velocity_Initial);
		p.SetDefaultValue("0");
		p.SetDescription("The initial velocity of the target in the velocity frame, the unit is m/s");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}
	{
		auto p = ADD_MODEL_PARAM(Accelerate_Initial);
		p.SetDefaultValue("0");
		p.SetDescription("The initial accelerate of the target in the velocity frame, the unit is m*m/s");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}
	{
		auto p = ADD_MODEL_ENUM_PARAM(IsRandomError, IsRandomErrorEnum);
		p.AddEnumeration("false", RADAR_TargetScatterLocation::RandomError_false);
		p.AddEnumeration("true", RADAR_TargetScatterLocation::RandomError_true);
		p.SetDefaultValue("false");
		p.SetDescription("Whether the random variance is considered");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}

	// --------- SimpleXYZ_Frame 参数 ---------
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Position_Initial_XYZ, Position_Initial_XYZSize);
		p.SetDefaultValue("[0 20e3 5e3]");
		p.SetUnit(SystemVueModelBuilder::Units::LENGTH);
		p.SetDescription("The target initial position which is defined in the Cartesian Coordinate System");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Velocity_Initial_XYZ, Velocity_Initial_XYZSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The initial velocity of the target");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Accelerate_XYZ, Accelerate_XYZSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The acceleration of the target");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Jerk_XYZ, Jerk_XYZSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The jerk of the target");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}

	// --------- 随机轨迹参数 ---------
	{
		auto p = ADD_MODEL_PARAM(Accelerate_Variance);
		p.SetDefaultValue("0");
		p.SetDescription("The velocity variance of the platform");
		p.SetHideCondition("Trajectory_Mode ~= 0 || IsRandomError ~= 1");
	}

	// --------- RCS 参数 ---------
	{
		auto p = ADD_MODEL_ARRAY_PARAM(RCS, RCSSize);
		p.SetDefaultValue("[1]");
		p.SetDescription("The RCS value of target scatters");
		p.SetHideCondition("Trajectory_Mode == 1");
	}
	{
		auto p = ADD_MODEL_ENUM_PARAM(IsRCSRandom, IsRCSRandomEnum);
		p.AddEnumeration("false", RADAR_TargetScatterLocation::RCSRandom_false);
		p.AddEnumeration("true", RADAR_TargetScatterLocation::RCSRandom_true);
		p.SetDefaultValue("false");
		p.SetDescription("Whether the random variance of RCS is considered");
		p.SetHideCondition("Trajectory_Mode == 1");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(RCS_Variance, RCS_VarianceSize);
		p.SetDefaultValue("[0]");
		p.SetDescription("The variance of the target scatter RCS");
		p.SetHideCondition("Trajectory_Mode == 1 || IsRCSRandom ~= 1");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(DurationTime, DurationTimeSize);
		p.SetDefaultValue("[1]");
		p.SetUnit(SystemVueModelBuilder::Units::TIME);
		p.SetDescription("The duration time between two random values");
		p.SetHideCondition("Trajectory_Mode == 1 || IsRCSRandom ~= 1");
	}

	// --------- 公共时间参数 ---------
	{
		auto p = ADD_MODEL_PARAM(TimeStep);
		p.SetDefaultValue("1e-9");
		p.SetUnit(SystemVueModelBuilder::Units::TIME);
		p.SetDescription("The time step value");
	}

	return true;
}
#endif // SV_CODE_GEN

RADAR_TargetScatterLocation::RADAR_TargetScatterLocation()
	: Trajectory_Mode(ECI_Frame)
	, NumberOfTargetScatter(1)
	, FileName(nullptr)
	, ScatterLoc(nullptr)
	, ScatterLocSize(0)
	, RCS(nullptr)
	, RCSSize(0)
	, IsRCSRandom(RCSRandom_false)
	, RCS_Variance(nullptr)
	, RCS_VarianceSize(0)
	, DurationTime(nullptr)
	, DurationTimeSize(0)
	, Position_Initial(nullptr)
	, Position_InitialSize(0)
	, Velocity_Initial(0.0)
	, Accelerate_Initial(0.0)
	, IsRandomError(RandomError_false)
	, Accelerate_Variance(0.0)
	, Position_Initial_XYZ(nullptr)
	, Position_Initial_XYZSize(0)
	, Velocity_Initial_XYZ(nullptr)
	, Velocity_Initial_XYZSize(0)
	, Accelerate_XYZ(nullptr)
	, Accelerate_XYZSize(0)
	, Jerk_XYZ(nullptr)
	, Jerk_XYZSize(0)
	, TimeStep(1e-9)
	, sampleIndex_(0ULL)
	, p0Ecef_(make_vec_(0.0, 0.0, 0.0))
	, eastEcef_(make_vec_(0.0, 1.0, 0.0))
	, northEcef_(make_vec_(0.0, 0.0, 1.0))
	, upEcef_(make_vec_(1.0, 0.0, 0.0))
	, motionAccumEcef_(make_vec_(0.0, 0.0, 0.0))
	, lonRad_(0.0)
	, latRad_(0.0)
	, userPathIndex_(0U)
{
	init_empty_user_sample_();
}

double RADAR_TargetScatterLocation::get_array_value_(const double* p, int size, int idx, double defval)
{
	if (p == nullptr || idx < 0 || idx >= size)
		return defval;
	return p[idx];
}

RADAR_TargetScatterLocation::Vec3 RADAR_TargetScatterLocation::make_vec_(double x, double y, double z)
{
	Vec3 v;
	v.x = x;
	v.y = y;
	v.z = z;
	return v;
}

RADAR_TargetScatterLocation::Vec3 RADAR_TargetScatterLocation::add_(const Vec3& a, const Vec3& b)
{
	return make_vec_(a.x + b.x, a.y + b.y, a.z + b.z);
}

RADAR_TargetScatterLocation::Vec3 RADAR_TargetScatterLocation::scale_(const Vec3& a, double s)
{
	return make_vec_(a.x * s, a.y * s, a.z * s);
}

double RADAR_TargetScatterLocation::dot_(const Vec3& a, const Vec3& b)
{
	return a.x * b.x + a.y * b.y + a.z * b.z;
}

RADAR_TargetScatterLocation::Vec3 RADAR_TargetScatterLocation::lla_to_ecef_(double lonRad, double latRad, double h)
{
	// 黑盒对齐版 LLA -> ECEF。与 RADAR_Platform 对齐版本保持一致。
	const double a = kEarthSemiMajorAxis;
	const double b = kEarthSemiMinorAxis;

	const double a2 = a * a;
	const double b2 = b * b;
	const double e2 = 1.0 - b2 / a2;

	const double sinLat = std::sin(latRad);
	const double cosLat = std::cos(latRad);
	const double sinLon = std::sin(lonRad);
	const double cosLon = std::cos(lonRad);

	const double N = a / std::sqrt(1.0 - e2 * sinLat * sinLat);

	const double x = (N + h) * cosLat * cosLon;
	const double y = (N + h) * cosLat * sinLon;
	const double z = (N * (1.0 - e2) + h) * sinLat;

	return make_vec_(x, y, z);
}

RADAR_TargetScatterLocation::Vec3 RADAR_TargetScatterLocation::rotate_z_(const Vec3& v, double theta)
{
	const double c = std::cos(theta);
	const double s = std::sin(theta);

	return make_vec_(
		c * v.x - s * v.y,
		s * v.x + c * v.y,
		v.z
	);
}

bool RADAR_TargetScatterLocation::validate_params_() const
{
	const int n = (NumberOfTargetScatter > 0) ? NumberOfTargetScatter : 1;

	if (Trajectory_Mode == ECI_Frame || Trajectory_Mode == SimpleXYZ_Frame)
	{
		if (ScatterLocSize != 3 * n)
		{
			std::cerr << "RADAR_TargetScatterLocation: The size of ScatterLoc should have 3*NumberOfTargetScatter elements and 3 elements for each target scatter." << std::endl;
			return false;
		}

		if (RCSSize != n)
		{
			std::cerr << "RADAR_TargetScatterLocation: The number of ScatterLoc Size should be kept consistent with the RCS_Size" << std::endl;
			return false;
		}
	}

	return true;
}

void RADAR_TargetScatterLocation::init_empty_user_sample_()
{
	const int n = (NumberOfTargetScatter > 0) ? NumberOfTargetScatter : 1;
	lastUserSample_.pos.assign(static_cast<std::size_t>(n), make_vec_(0.0, 0.0, 0.0));
	lastUserSample_.rcs.assign(static_cast<std::size_t>(n), 0.0);
}

bool RADAR_TargetScatterLocation::load_user_file_()
{
	userPath_.clear();
	userPathIndex_ = 0U;
	init_empty_user_sample_();

	const int n = (NumberOfTargetScatter > 0) ? NumberOfTargetScatter : 1;

	if (FileName == nullptr || FileName[0] == '\0')
		return true;

	std::ifstream fin(FileName);
	if (!fin)
		return true;

	std::string line;
	while (std::getline(fin, line))
	{
		std::istringstream iss(line);
		UserSample sample;
		sample.pos.reserve(static_cast<std::size_t>(n));
		sample.rcs.reserve(static_cast<std::size_t>(n));

		bool ok = true;
		for (int i = 0; i < n; ++i)
		{
			double x = 0.0;
			double y = 0.0;
			double z = 0.0;
			double r = 0.0;
			if (!(iss >> x >> y >> z >> r))
			{
				ok = false;
				break;
			}
			sample.pos.push_back(make_vec_(x, y, z));
			sample.rcs.push_back(r);
		}

		if (ok && static_cast<int>(sample.pos.size()) == n)
			userPath_.push_back(sample);
	}

	if (!userPath_.empty())
		lastUserSample_ = userPath_.front();

	return true;
}

RADAR_TargetScatterLocation::Vec3 RADAR_TargetScatterLocation::get_scatter_loc_(int idx) const
{
	return make_vec_(
		get_array_value_(ScatterLoc, ScatterLocSize, 3 * idx + 0, 0.0),
		get_array_value_(ScatterLoc, ScatterLocSize, 3 * idx + 1, 0.0),
		get_array_value_(ScatterLoc, ScatterLocSize, 3 * idx + 2, 0.0)
	);
}

double RADAR_TargetScatterLocation::get_rcs_base_(int idx) const
{
	return get_array_value_(RCS, RCSSize, idx, 1.0);
}

double RADAR_TargetScatterLocation::base_random_position_(unsigned long long k) const
{
	// 与 RADAR_Platform 轨迹随机误差保持一致的固定基序列。
	static const double table[] =
	{
		0.205548047910945,
		0.11099594587191,
		0.57205602872446,
		0.586286278195218,
		-0.182779648757732,
		0.00569209978830308,
		-0.0411096095821889,
		-0.409198729225788,
		0.113209540234028,
		0.00505964425626941,
		-0.343107126128269,
		0.334885204211831,
		0.0986630629972534,
		-0.03699864862397,
		-0.179617371097564,
		-0.49900741477457,
		-0.491417948390166,
		-0.668821725125612,
		-0.877215822930708,
		-0.65806998108104,
		-0.0610319588412497,
		0.330458015487596,
		0.317808904846922,
		-0.576483217448695,
		-0.811124219833189,
		-0.453786844234162,
		-0.985998174440501,
		-1.24783476470244,
		-1.45749377357161,
		-1.84771883683638,
		-1.56754103614547,
		-1.92045122302026,
		-1.20040059979992,
		-1.35124124418995,
		-1.74273121851879,
		-1.83443727066368,
		-1.97168012111498,
		-2.62563914123781,
		-3.62586756514906,
		-4.13531049620219,
		-3.23817232401242,
		-3.81307440263103,
		-2.88178363171144,
		-2.93965331289253,
		-2.9523024235332,
		-2.55670148824613,
		-1.93341656142695,
		-0.873737317504523,
		-1.42903327463009,
		-1.99729457016235
	};
	const unsigned long long nTable = static_cast<unsigned long long>(sizeof(table) / sizeof(table[0]));
	if (k < nTable)
		return table[k];

	unsigned long long x = 1469598103934665603ULL ^ (k + 0x9e3779b97f4a7c15ULL);
	x ^= x >> 12;
	x ^= x << 25;
	x ^= x >> 27;
	const unsigned long long y = x * 2685821657736338717ULL;
	const double u = (static_cast<double>((y >> 11) & 0x1FFFFFFFFFFFFFULL) + 1.0)
		/ 9007199254740992.0;
	return 2.0 * u - 1.0;
}

double RADAR_TargetScatterLocation::base_random_rcs_(unsigned long long blockIndex, int scatterIndex) const
{
	// RCS 随机基序列由黑盒 RR3/RR4 反推。
	// RCS_out = RCS + RCS_Variance * baseRandom。
	// 前三项对应 RR3-1 的 10.411、9.811、10.922。
	static const double table[] =
	{
		0.41125,
		-0.18900,
		0.92200,
		-0.75600,
		0.33700,
		-0.50800,
		0.61400,
		-0.27100,
		0.14300,
		-0.43600
	};

	const unsigned long long nTable = static_cast<unsigned long long>(sizeof(table) / sizeof(table[0]));
	if (blockIndex < nTable)
		return table[blockIndex];

	unsigned long long x = 1099511628211ULL * static_cast<unsigned long long>(scatterIndex + 1);
	x ^= (blockIndex + 0x9e3779b97f4a7c15ULL);
	x ^= x >> 12;
	x ^= x << 25;
	x ^= x >> 27;
	const unsigned long long y = x * 2685821657736338717ULL;
	const double u = (static_cast<double>((y >> 11) & 0x1FFFFFFFFFFFFFULL) + 1.0)
		/ 9007199254740992.0;
	return 2.0 * u - 1.0;
}

double RADAR_TargetScatterLocation::calc_scatter_rcs_(int idx, unsigned long long k) const
{
	const double base = get_rcs_base_(idx);

	if (IsRCSRandom != RCSRandom_true)
		return base;

	// 黑盒 RR5：DurationTime 不自动广播。某个 scatter 没有对应 DurationTime 时，不产生随机 RCS。
	if (DurationTime == nullptr || idx < 0 || idx >= DurationTimeSize)
		return base;

	if (RCS_Variance == nullptr || idx >= RCS_VarianceSize)
		return base;

	const double variance = RCS_Variance[idx];
	if (variance == 0.0)
		return base;

	const double dur = DurationTime[idx];
	if (dur <= 0.0 || TimeStep <= 0.0)
		return base;

	// DurationTime 以秒为单位。换算成 sample 数。
	// 黑盒结果：DurationTime=1, TimeStep=1 时 k=0,1 保持基准；k=2 开始第一个随机值。
	// DurationTime=3, TimeStep=1 时 k=0..3 保持基准；k=4..6 为第一个随机值。
	long long durSamples = static_cast<long long>(std::floor(dur / TimeStep + 1.0e-12));
	if (durSamples < 1)
		durSamples = 1;

	const unsigned long long holdSamples = static_cast<unsigned long long>(durSamples + 1);
	if (k < holdSamples)
		return base;

	const unsigned long long blockIndex = (k - holdSamples) / static_cast<unsigned long long>(durSamples);
	return base + variance * base_random_rcs_(blockIndex, idx);
}

void RADAR_TargetScatterLocation::write_outputs_(const std::vector<Vec3>& positions, const std::vector<double>& rcsValues)
{
	const int nParam = (NumberOfTargetScatter > 0) ? NumberOfTargetScatter : 1;

	// bus 输出通道数由连接到该端口的 bus 通道数决定。
	// 为避免未连接通道导致越界，只对实际存在的通道写出；
	// 正常验证时应让 Pos 和 ScatterRCS 都连接 NumberOfTargetScatter 个通道。
	const int nPosBus = Pos.GetSize();
	const int nRcsBus = ScatterRCS.GetSize();

	const int nPosWrite = std::min(nParam, nPosBus);
	const int nRcsWrite = std::min(nParam, nRcsBus);

	for (int i = 0; i < nPosWrite; ++i)
	{
		const Vec3 p = (i < static_cast<int>(positions.size()))
			? positions[static_cast<std::size_t>(i)]
			: make_vec_(0.0, 0.0, 0.0);

		SystemVueModelBuilder::DoubleMatrix m(3, 1);
		m(0, 0) = p.x;
		m(1, 0) = p.y;
		m(2, 0) = p.z;

		Pos[i][0U] = m;
	}

	for (int i = 0; i < nRcsWrite; ++i)
	{
		const double r = (i < static_cast<int>(rcsValues.size()))
			? rcsValues[static_cast<std::size_t>(i)]
			: 0.0;

		ScatterRCS[i][0U] = r;
	}
}

bool RADAR_TargetScatterLocation::Setup()
{
	if (NumberOfTargetScatter <= 0)
		NumberOfTargetScatter = 1;

	sampleIndex_ = 0ULL;
	motionAccumEcef_ = make_vec_(0.0, 0.0, 0.0);
	userPathIndex_ = 0U;

	// Pos / ScatterRCS 是真正的 bus 输出端口。
	// bus 通道数由 SystemVue 连接关系决定；这里不再用 SetRate() 模拟多通道。
	// 每个已连接的 bus 通道每次 Run() 输出 1 个 token。

	if (!validate_params_())
		return false;

	// 初始化 ECI 模式使用的坐标常量。
	const double lonDeg = get_array_value_(Position_Initial, Position_InitialSize, 0, 0.0);
	const double latDeg = get_array_value_(Position_Initial, Position_InitialSize, 1, 0.0);
	const double h = get_array_value_(Position_Initial, Position_InitialSize, 2, 0.0);

	lonRad_ = lonDeg * kDegToRad;
	latRad_ = latDeg * kDegToRad;

	p0Ecef_ = lla_to_ecef_(lonRad_, latRad_, h);

	const double sinLon = std::sin(lonRad_);
	const double cosLon = std::cos(lonRad_);
	const double sinLat = std::sin(latRad_);
	const double cosLat = std::cos(latRad_);

	eastEcef_ = make_vec_(-sinLon, cosLon, 0.0);
	northEcef_ = make_vec_(-sinLat * cosLon, -sinLat * sinLon, cosLat);
	upEcef_ = make_vec_(cosLat * cosLon, cosLat * sinLon, sinLat);

	load_user_file_();

	return true;
}

bool RADAR_TargetScatterLocation::Run()
{
	const int n = (NumberOfTargetScatter > 0) ? NumberOfTargetScatter : 1;

	if (Trajectory_Mode == User_Defined)
	{
		UserSample out = lastUserSample_;
		if (!userPath_.empty())
		{
			if (userPathIndex_ < userPath_.size())
			{
				out = userPath_[userPathIndex_];
				lastUserSample_ = out;
				++userPathIndex_;
			}
			else
			{
				out = lastUserSample_;
			}
		}

		write_outputs_(out.pos, out.rcs);
		++sampleIndex_;
		return true;
	}

	if (Trajectory_Mode == SimpleXYZ_Frame)
	{
		const double k = static_cast<double>(sampleIndex_);
		const double t = k * TimeStep;
		const double t2 = t * t;
		const double t3 = t2 * t;

		const double x0 = get_array_value_(Position_Initial_XYZ, Position_Initial_XYZSize, 0, 0.0);
		const double y0 = get_array_value_(Position_Initial_XYZ, Position_Initial_XYZSize, 1, 20e3);
		const double z0 = get_array_value_(Position_Initial_XYZ, Position_Initial_XYZSize, 2, 5e3);

		const double vx = get_array_value_(Velocity_Initial_XYZ, Velocity_Initial_XYZSize, 0, 0.0);
		const double vy = get_array_value_(Velocity_Initial_XYZ, Velocity_Initial_XYZSize, 1, 0.0);
		const double vz = get_array_value_(Velocity_Initial_XYZ, Velocity_Initial_XYZSize, 2, 0.0);

		const double ax = get_array_value_(Accelerate_XYZ, Accelerate_XYZSize, 0, 0.0);
		const double ay = get_array_value_(Accelerate_XYZ, Accelerate_XYZSize, 1, 0.0);
		const double az = get_array_value_(Accelerate_XYZ, Accelerate_XYZSize, 2, 0.0);

		const double jx = get_array_value_(Jerk_XYZ, Jerk_XYZSize, 0, 0.0);
		const double jy = get_array_value_(Jerk_XYZ, Jerk_XYZSize, 1, 0.0);
		const double jz = get_array_value_(Jerk_XYZ, Jerk_XYZSize, 2, 0.0);

		const Vec3 center = make_vec_(
			x0 + vx * t + 0.5 * ax * t2 + (jx * t3 / 3.0),
			y0 + vy * t + 0.5 * ay * t2 + (jy * t3 / 3.0),
			z0 + vz * t + 0.5 * az * t2 + (jz * t3 / 3.0)
		);

		std::vector<Vec3> positions;
		std::vector<double> rcsValues;
		positions.reserve(static_cast<std::size_t>(n));
		rcsValues.reserve(static_cast<std::size_t>(n));

		for (int i = 0; i < n; ++i)
		{
			const Vec3 sc = get_scatter_loc_(i);
			positions.push_back(add_(center, sc));
			rcsValues.push_back(calc_scatter_rcs_(i, sampleIndex_));
		}

		write_outputs_(positions, rcsValues);
		++sampleIndex_;
		return true;
	}

	// --------- ECI_Frame ---------
	const double rollDeg = Roll[0];
	const double pitchDeg = Pitch[0];
	const double yawDeg = Yaw[0];

	const double roll = rollDeg * kDegToRad;
	const double pitch = pitchDeg * kDegToRad;
	const double yaw = yawDeg * kDegToRad;

	const double cosRoll = std::cos(roll);
	const double sinRoll = std::sin(roll);
	const double cosPitch = std::cos(pitch);
	const double sinPitch = std::sin(pitch);
	const double cosYaw = std::cos(yaw);
	const double sinYaw = std::sin(yaw);

	// 质心运动方向复用 RADAR_Platform：yaw=0 指向 North，yaw=+90 指向 East，pitch=+90 指向 Up。
	const double dirEast = cosPitch * sinYaw;
	const double dirNorth = cosPitch * cosYaw;
	const double dirUp = sinPitch;

	Vec3 dirEcef = add_(
		add_(scale_(eastEcef_, dirEast), scale_(northEcef_, dirNorth)),
		scale_(upEcef_, dirUp)
	);

	const double norm2 = dot_(dirEcef, dirEcef);
	if (norm2 > 0.0)
		dirEcef = scale_(dirEcef, 1.0 / std::sqrt(norm2));

	const double stepDistance =
		Velocity_Initial * TimeStep
		+ 0.5 * Accelerate_Initial * TimeStep * TimeStep;

	motionAccumEcef_ = add_(motionAccumEcef_, scale_(dirEcef, stepDistance));

	double randomDistance = 0.0;
	if (IsRandomError == RandomError_true && Accelerate_Variance > 0.0)
	{
		randomDistance = std::sqrt(Accelerate_Variance) * base_random_position_(sampleIndex_);
	}

	const Vec3 centerMovedEcef = add_(
		p0Ecef_,
		add_(motionAccumEcef_, scale_(dirEcef, randomDistance))
	);

	const double theta = kEarthRotationRate * static_cast<double>(sampleIndex_) * TimeStep;

	std::vector<Vec3> positions;
	std::vector<double> rcsValues;
	positions.reserve(static_cast<std::size_t>(n));
	rcsValues.reserve(static_cast<std::size_t>(n));

	for (int i = 0; i < n; ++i)
	{
		const Vec3 sc = get_scatter_loc_(i);

		// 黑盒对齐：ECI_Frame 下 ScatterLoc 是 body frame 坐标。
		// body 轴定义：x=forward, y=right, z=down。
		// 局部坐标采用 NED：North, East, Down。
		// 先使用 Roll/Pitch/Yaw 将 ScatterLoc 从 body frame 旋转到局部 NED frame。
		const double sxBody = sc.x;
		const double syBody = sc.y;
		const double szBody = sc.z;

		const double nLoc =
			cosPitch * cosYaw * sxBody
			+ (sinRoll * sinPitch * cosYaw - cosRoll * sinYaw) * syBody
			+ (cosRoll * sinPitch * cosYaw + sinRoll * sinYaw) * szBody;

		const double eLoc =
			cosPitch * sinYaw * sxBody
			+ (sinRoll * sinPitch * sinYaw + cosRoll * cosYaw) * syBody
			+ (cosRoll * sinPitch * sinYaw - sinRoll * cosYaw) * szBody;

		const double dLoc =
			-sinPitch * sxBody
			+ sinRoll * cosPitch * syBody
			+ cosRoll * cosPitch * szBody;

		// NED -> ECEF：
		// N 对应 northEcef_，E 对应 eastEcef_，D 对应 -upEcef_。
		// 再与质心 ECEF 坐标相加，最后整体旋转到 ECI。
		const Vec3 scatterOffsetEcef = add_(
			add_(scale_(northEcef_, nLoc), scale_(eastEcef_, eLoc)),
			scale_(upEcef_, -dLoc)
		);

		const Vec3 scatterEcef = add_(centerMovedEcef, scatterOffsetEcef);
		const Vec3 pos = rotate_z_(scatterEcef, theta);

		positions.push_back(pos);
		rcsValues.push_back(calc_scatter_rcs_(i, sampleIndex_));
	}

	write_outputs_(positions, rcsValues);
	++sampleIndex_;
	return true;
}