#include "RADAR_Platform.h"

#include <fstream>
#include <sstream>
#include <iostream>
#include <cstdlib>
#include <cstring>

const double RADAR_Platform::kPi = 3.1415926535897932384626433832795;
const double RADAR_Platform::kDegToRad = RADAR_Platform::kPi / 180.0;

// 黑盒对齐后的地球椭球和自转常量。
const double RADAR_Platform::kEarthSemiMajorAxis = 6378137.0;
const double RADAR_Platform::kEarthSemiMinorAxis = 6356752.0;
const double RADAR_Platform::kEarthRotationRate = 7.2921151467e-5;

#ifndef SV_CODE_GEN
DEFINE_MODEL_INTERFACE(RADAR_Platform)
{
	SET_MODEL_DESCRIPTION("Platform Trajectory");
	SET_MODEL_CATEGORY("Radar");

	// --------- 端口 ---------
	// 先添加输出端口，使 Pos 为端口 1。
	{
		auto p = ADD_MODEL_OUTPUT(Pos);
		p.SetDescription("Platform position value in ECI frame");
	}

	// 再按内置帮助文档的端口号顺序添加可选输入：
	// Port 2 = Roll, Port 3 = Pitch, Port 4 = Yaw。
	{
		auto p = ADD_MODEL_INPUT(Roll);
		p.SetDescription("The roll angle of radar body frame (deg)");
		p.SetOptional(true);
	}
	{
		auto p = ADD_MODEL_INPUT(Pitch);
		p.SetDescription("The pitch angle of radar body frame (deg)");
		p.SetOptional(true);
	}
	{
		auto p = ADD_MODEL_INPUT(Yaw);
		p.SetDescription("The yaw angle of radar body frame (deg)");
		p.SetOptional(true);
	}

	// --------- Trajectory_Mode ---------
	{
		auto p = ADD_MODEL_ENUM_PARAM(Trajectory_Mode, Trajectory_ModeEnum);
		p.AddEnumeration("ECI_Frame", RADAR_Platform::ECI_Frame);
		p.AddEnumeration("User Defined", RADAR_Platform::User_Defined);
		p.AddEnumeration("SimpleXYZ_Frame", RADAR_Platform::SimpleXYZ_Frame);
		p.SetDefaultValue("ECI_Frame");
		p.SetDescription("The mode oftrajectory generation:ECL Frame: the outputin the ECI frame is generated in this model; UserDefined Users canimport the file which trajectory in ECl frame is generated by users; SimpleXYZ_ Frame: the output under Cartesian coordinate isgenerated in this model");
	}

	// --------- ECI_Frame 参数 ---------
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Position_Initial, Position_InitialSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The radar initial position which is defined in the LLAFrame. [longitude(deg), latitude(deg), height(m)]");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}
	{
		auto p = ADD_MODEL_PARAM(Velocity_Initial);
		p.SetDefaultValue("0");
		p.SetDescription("The initial velocity of the platform in the velocity frame of radar, the unit is m/s");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}
	{
		auto p = ADD_MODEL_PARAM(Accelerate_Initial);
		p.SetDefaultValue("0");
		p.SetDescription("The accelerate of the platform in the velocity frame of radar, the unit is m*m/s");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}
	{
		auto p = ADD_MODEL_ENUM_PARAM(IsRandomError, IsRandomErrorEnum);
		p.AddEnumeration("IRE_false", RADAR_Platform::IRE_false);
		p.AddEnumeration("IRE_true", RADAR_Platform::IRE_true);
		p.SetDefaultValue("IRE_false");
		p.SetDescription("Whether the random variance is considered");
		p.SetHideCondition("Trajectory_Mode ~= 0");
	}

	// 注意：内置模型中该参数只受 IsRandomError 控制。
	// 因此当在 ECI 模式下把 IsRandomError 设为 true 后，
	// 切换到 User Defined 或 SimpleXYZ_Frame 时，IsRandomError 本身会隐藏，
	// 但 Accelerate_Variance 仍会显示。
	{
		auto p = ADD_MODEL_PARAM(Accelerate_Variance);
		p.SetDefaultValue("0");
		p.SetDescription("The velocity variance of the platform. This parameter is available only when IsRandomError is set to true.");
		p.SetHideCondition("Trajectory_Mode ~= 0 || IsRandomError ~= 1");
	}

	// --------- User Defined 参数 ---------
	{
		SystemVueModelBuilder::DFParam p = ADD_MODEL_PARAM(FileName);
		p.SetDefaultValue("");
		p.SetDescription("The platform location file path. The each line format in the file is X Y Z or latitudeX longitudeX heightX");
		p.SetParamAsFile();
		p.SetHideCondition("Trajectory_Mode ~= 1");
	}

	// --------- SimpleXYZ_Frame 参数 ---------
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Position_Initial_XYZ, Position_Initial_XYZSize);
		p.SetDefaultValue("[0 20e3 5e3]");
		p.SetUnit(SystemVueModelBuilder::Units::LENGTH);
		p.SetDescription("The initial position in the simple XYZ frame");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Velocity_Initial_XYZ, Velocity_Initial_XYZSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The initial velocity of the target");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Accelerate_XYZ, Accelerate_XYZSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The accelerate of the target");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}
	{
		auto p = ADD_MODEL_ARRAY_PARAM(Jerk_XYZ, Jerk_XYZSize);
		p.SetDefaultValue("[0 0 0]");
		p.SetDescription("The jerk of the target");
		p.SetHideCondition("Trajectory_Mode ~= 2");
	}

	// --------- 公共参数 ---------
	{
		auto p = ADD_MODEL_PARAM(TimeStep);
		p.SetDefaultValue("1e-9");
		p.SetUnit(SystemVueModelBuilder::Units::TIME);
		p.SetDescription("The time step value");
	}
	{
		auto p = ADD_MODEL_ENUM_PARAM(PrintLog, PrintLogEnum);
		p.AddEnumeration("PrintLog_No", RADAR_Platform::PrintLog_No);
		p.AddEnumeration("PrintLog_Yes", RADAR_Platform::PrintLog_Yes);
		p.SetDefaultValue("PrintLog_No");
		p.SetDescription("Whether print log information");
	}

	return true;
}
#endif // SV_CODE_GEN

RADAR_Platform::RADAR_Platform(): Trajectory_Mode(ECI_Frame), 
    PrintLog(PrintLog_No),
	Position_Initial(nullptr), 
	Position_InitialSize(0), 
	Velocity_Initial(0.0), 
	Accelerate_Initial(0.0), 
	IsRandomError(IRE_false),
	Accelerate_Variance(0.0), 
	FileName(nullptr), 
	Position_Initial_XYZ(nullptr), 
	Position_Initial_XYZSize(0), 
	Velocity_Initial_XYZ(nullptr), 
	Velocity_Initial_XYZSize(0), 
	Accelerate_XYZ(nullptr), 
	Accelerate_XYZSize(0), 
	Jerk_XYZ(nullptr), 
	Jerk_XYZSize(0), 
	TimeStep(1e-9), 
	sampleIndex_(0ULL), 
	p0Ecef_(make_vec_(0.0, 0.0, 0.0)), 
	eastEcef_(make_vec_(0.0, 1.0, 0.0)), 
	northEcef_(make_vec_(0.0, 0.0, 1.0)), 
	upEcef_(make_vec_(1.0, 0.0, 0.0)), 
	motionAccumEcef_(make_vec_(0.0, 0.0, 0.0)), 
	lonRad_(0.0), 
	latRad_(0.0), 
	userPathIndex_(0U), 
	lastUserPos_(make_vec_(0.0, 0.0, 0.0))
{
}

double RADAR_Platform::get_array_value_(const double* p, int size, int idx, double defval)
{
	if (p == nullptr || idx < 0 || idx >= size)
		return defval;
	return p[idx];
}

RADAR_Platform::Vec3 RADAR_Platform::make_vec_(double x, double y, double z)
{
	Vec3 v;
	v.x = x;
	v.y = y;
	v.z = z;
	return v;
}

RADAR_Platform::Vec3 RADAR_Platform::add_(const Vec3& a, const Vec3& b)
{
	return make_vec_(a.x + b.x, a.y + b.y, a.z + b.z);
}

RADAR_Platform::Vec3 RADAR_Platform::scale_(const Vec3& a, double s)
{
	return make_vec_(a.x * s, a.y * s, a.z * s);
}

double RADAR_Platform::dot_(const Vec3& a, const Vec3& b)
{
	return a.x * b.x + a.y * b.y + a.z * b.z;
}

RADAR_Platform::Vec3 RADAR_Platform::lla_to_ecef_(double lonRad, double latRad, double h)
{
	// 黑盒对齐版 LLA -> ECEF。
	// 内置 RADAR_Platform 的极点和非零经纬度误差表明：
	// 其椭球更接近 a=6378137.0、b=6356752.0，
	// 而不是完整 WGS84 半短轴 6356752.314245...。
	const double a = kEarthSemiMajorAxis;
	const double b = kEarthSemiMinorAxis;

	const double a2 = a * a;
	const double b2 = b * b;
	const double e2 = 1.0 - b2 / a2;

	const double sinLat = std::sin(latRad);
	const double cosLat = std::cos(latRad);
	const double sinLon = std::sin(lonRad);
	const double cosLon = std::cos(lonRad);

	const double N = a / std::sqrt(1.0 - e2 * sinLat * sinLat);

	const double x = (N + h) * cosLat * cosLon;
	const double y = (N + h) * cosLat * sinLon;
	const double z = (N * (1.0 - e2) + h) * sinLat;

	return make_vec_(x, y, z);
}

RADAR_Platform::Vec3 RADAR_Platform::rotate_z_(const Vec3& v, double theta)
{
	// ECEF -> ECI 的地球自转旋转。
	// 黑盒结果对应 Rz(+omega*t)。
	const double c = std::cos(theta);
	const double s = std::sin(theta);

	return make_vec_(
		c * v.x - s * v.y,
		s * v.x + c * v.y,
		v.z
	);
}

void RADAR_Platform::write_pos_(double x, double y, double z)
{
	// 内置 RADAR_Platform 的 Pos 是 real matrix。
	// 每次 Run() 输出一个 3x1 DoubleMatrix token：row0=X、row1=Y、row2=Z。
	SystemVueModelBuilder::DoubleMatrix m(3, 1);

	m(0, 0) = x;
	m(1, 0) = y;
	m(2, 0) = z;

	Pos[0] = m;
}

bool RADAR_Platform::load_user_file_()
{
	userPath_.clear();
	userPathIndex_ = 0U;
	lastUserPos_ = make_vec_(0.0, 0.0, 0.0);

	if (FileName == nullptr || FileName[0] == '\0')
	{
		if (PrintLog == PrintLog_Yes)
			std::cout << "RADAR_Platform: FileName is empty." << std::endl;
		return true;
	}

	std::ifstream fin(FileName);
	if (!fin)
	{
		if (PrintLog == PrintLog_Yes)
			std::cout << "RADAR_Platform: failed to open file: " << FileName << std::endl;
		return true;
	}

	std::string line;
	while (std::getline(fin, line))
	{
		// 内置模型更接近空白符分隔读取方式，不按 CSV 解析。
		// 因此 "100,200,300" 不是合法的三列输入格式。
		std::istringstream iss(line);
		double x = 0.0;
		double y = 0.0;
		double z = 0.0;

		if (iss >> x >> y >> z)
		{
			userPath_.push_back(make_vec_(x, y, z));
		}
	}

	if (!userPath_.empty())
		lastUserPos_ = userPath_.front();

	if (PrintLog == PrintLog_Yes)
		std::cout << "RADAR_Platform: loaded " << userPath_.size() << " user trajectory points." << std::endl;

	return true;
}

double RADAR_Platform::base_random_(unsigned long long k) const
{
	// 黑盒反推得到的固定随机基序列。
	// randomOffset = sqrt(Accelerate_Variance) * baseRandom[k]。
	// 前 50 个值由内置 RADAR_Platform 的 H3/R5 测试反推。
	static const double table[] =
	{
		0.205548047910945,
		0.11099594587191,
		0.57205602872446,
		0.586286278195218,
		-0.182779648757732,
		0.00569209978830308,
		-0.0411096095821889,
		-0.409198729225788,
		0.113209540234028,
		0.00505964425626941,
		-0.343107126128269,
		0.334885204211831,
		0.0986630629972534,
		-0.03699864862397,
		-0.179617371097564,
		-0.49900741477457,
		-0.491417948390166,
		-0.668821725125612,
		-0.877215822930708,
		-0.65806998108104,
		-0.0610319588412497,
		0.330458015487596,
		0.317808904846922,
		-0.576483217448695,
		-0.811124219833189,
		-0.453786844234162,
		-0.985998174440501,
		-1.24783476470244,
		-1.45749377357161,
		-1.84771883683638,
		-1.56754103614547,
		-1.92045122302026,
		-1.20040059979992,
		-1.35124124418995,
		-1.74273121851879,
		-1.83443727066368,
		-1.97168012111498,
		-2.62563914123781,
		-3.62586756514906,
		-4.13531049620219,
		-3.23817232401242,
		-3.81307440263103,
		-2.88178363171144,
		-2.93965331289253,
		-2.9523024235332,
		-2.55670148824613,
		-1.93341656142695,
		-0.873737317504523,
		-1.42903327463009,
		-1.99729457016235
	};
	const unsigned long long nTable = static_cast<unsigned long long>(sizeof(table) / sizeof(table[0]));
	if (k < nTable)
		return table[k];

	// 超出已反推表长后的确定性备用序列。
	// 该部分只能保证可重复，不能保证与内置模型逐点一致；
	// 若随机误差也要求长序列精确对齐，需要继续扩展上面的黑盒随机表。
	unsigned long long x = 1469598103934665603ULL ^ (k + 0x9e3779b97f4a7c15ULL);
	x ^= x >> 12;
	x ^= x << 25;
	x ^= x >> 27;
	const unsigned long long y = x * 2685821657736338717ULL;

	const double u = (static_cast<double>((y >> 11) & 0x1FFFFFFFFFFFFFULL) + 1.0)
		/ 9007199254740992.0;

	// 简单映射到近似零均值范围，避免引入非确定状态。
	return 2.0 * u - 1.0;
}

bool RADAR_Platform::Setup()
{
	sampleIndex_ = 0ULL;
	motionAccumEcef_ = make_vec_(0.0, 0.0, 0.0);

	// Pos 是 real matrix 输出端口：每次 Run() 输出 1 个 3x1 矩阵 token。
	Pos.SetRate(1);

	// 初始化 ECI 模式使用的坐标常量。
	const double lonDeg = get_array_value_(Position_Initial, Position_InitialSize, 0, 0.0);
	const double latDeg = get_array_value_(Position_Initial, Position_InitialSize, 1, 0.0);
	const double h = get_array_value_(Position_Initial, Position_InitialSize, 2, 0.0);

	lonRad_ = lonDeg * kDegToRad;
	latRad_ = latDeg * kDegToRad;

	p0Ecef_ = lla_to_ecef_(lonRad_, latRad_, h);

	const double sinLon = std::sin(lonRad_);
	const double cosLon = std::cos(lonRad_);
	const double sinLat = std::sin(latRad_);
	const double cosLat = std::cos(latRad_);

	eastEcef_ = make_vec_(-sinLon, cosLon, 0.0);
	northEcef_ = make_vec_(-sinLat * cosLon, -sinLat * sinLon, cosLat);
	upEcef_ = make_vec_(cosLat * cosLon, cosLat * sinLon, sinLat);

	// 初始化 User Defined 模式轨迹文件。
	load_user_file_();

	if (PrintLog == PrintLog_Yes)
	{
		std::cout << "RADAR_Platform Setup: mode=" << static_cast<int>(Trajectory_Mode)
			<< ", TimeStep=" << TimeStep << std::endl;
	}

	return true;
}

bool RADAR_Platform::Run()
{
	if (Trajectory_Mode == SimpleXYZ_Frame)
	{
		// SimpleXYZ_Frame：第 0 帧为初始位置，t = k * TimeStep。
		const double k = static_cast<double>(sampleIndex_);
		const double t = k * TimeStep;
		const double t2 = t * t;
		const double t3 = t2 * t;

		const double x0 = get_array_value_(Position_Initial_XYZ, Position_Initial_XYZSize, 0, 0.0);
		const double y0 = get_array_value_(Position_Initial_XYZ, Position_Initial_XYZSize, 1, 20e3);
		const double z0 = get_array_value_(Position_Initial_XYZ, Position_Initial_XYZSize, 2, 5e3);

		const double vx = get_array_value_(Velocity_Initial_XYZ, Velocity_Initial_XYZSize, 0, 0.0);
		const double vy = get_array_value_(Velocity_Initial_XYZ, Velocity_Initial_XYZSize, 1, 0.0);
		const double vz = get_array_value_(Velocity_Initial_XYZ, Velocity_Initial_XYZSize, 2, 0.0);

		const double ax = get_array_value_(Accelerate_XYZ, Accelerate_XYZSize, 0, 0.0);
		const double ay = get_array_value_(Accelerate_XYZ, Accelerate_XYZSize, 1, 0.0);
		const double az = get_array_value_(Accelerate_XYZ, Accelerate_XYZSize, 2, 0.0);

		const double jx = get_array_value_(Jerk_XYZ, Jerk_XYZSize, 0, 0.0);
		const double jy = get_array_value_(Jerk_XYZ, Jerk_XYZSize, 1, 0.0);
		const double jz = get_array_value_(Jerk_XYZ, Jerk_XYZSize, 2, 0.0);

		// 黑盒对齐：jerk 项系数为 1/3，不是常规运动学中的 1/6。
		const double x = x0 + vx * t + 0.5 * ax * t2 + (jx * t3 / 3.0);
		const double y = y0 + vy * t + 0.5 * ay * t2 + (jy * t3 / 3.0);
		const double z = z0 + vz * t + 0.5 * az * t2 + (jz * t3 / 3.0);

		write_pos_(x, y, z);

		++sampleIndex_;
		return true;
	}

	if (Trajectory_Mode == User_Defined)
	{
		Vec3 out = lastUserPos_;

		if (!userPath_.empty())
		{
			if (userPathIndex_ < userPath_.size())
			{
				out = userPath_[userPathIndex_];
				lastUserPos_ = out;
				++userPathIndex_;
			}
			else
			{
				// 文件结束后保持最后一个有效轨迹点。
				out = lastUserPos_;
			}
		}

		write_pos_(out.x, out.y, out.z);

		++sampleIndex_;
		return true;
	}

	// --------- ECI_Frame ---------

	// 可选输入端口未连接时，SystemVue 内置行为等效为 0。
	// 这里直接读取输入 token；在常见 Model Builder 数据流中未连接可选输入为 0。
	const double rollDeg = Roll[0];      // 对 Pos 不起作用，保留读取以匹配接口。
	(void)rollDeg;

	const double pitchDeg = Pitch[0];
	const double yawDeg = Yaw[0];

	const double pitch = pitchDeg * kDegToRad;
	const double yaw = yawDeg * kDegToRad;

	const double cosPitch = std::cos(pitch);

	// 黑盒对齐的 ENU 方向：
	// yaw=0 指向 North；yaw=+90 指向 East；pitch=+90 指向 Up。
	const double dirEast = cosPitch * std::sin(yaw);
	const double dirNorth = cosPitch * std::cos(yaw);
	const double dirUp = std::sin(pitch);

	Vec3 dirEcef = add_(
		add_(scale_(eastEcef_, dirEast), scale_(northEcef_, dirNorth)),
		scale_(upEcef_, dirUp)
	);

	// 为减少数值漂移，做一次单位化。理论上 ENU 基向量正交归一。
	const double norm2 = dot_(dirEcef, dirEcef);
	if (norm2 > 0.0)
		dirEcef = scale_(dirEcef, 1.0 / std::sqrt(norm2));

	// ECI_Frame 的确定性运动不是全局二次积分，
	// 而是每个 sample 固定推进：
	// V*Ts + 0.5*A*Ts^2。
	const double stepDistance =
		Velocity_Initial * TimeStep
		+ 0.5 * Accelerate_Initial * TimeStep * TimeStep;

	// 第 0 帧已经推进一次平台自身运动，因此先累加，再输出。
	motionAccumEcef_ = add_(motionAccumEcef_, scale_(dirEcef, stepDistance));

	// 随机误差：沿当前 yaw/pitch 定义的 forward 方向加入瞬时位置扰动。
	double randomDistance = 0.0;
	if (IsRandomError && Accelerate_Variance > 0.0)
	{
		randomDistance = std::sqrt(Accelerate_Variance) * base_random_(sampleIndex_);
	}

	Vec3 localMovedPosition = add_(
		p0Ecef_,
		add_(motionAccumEcef_, scale_(dirEcef, randomDistance))
	);

	// 地球自转：旋转整个位移后的 ECEF 向量。
	const double theta = kEarthRotationRate * static_cast<double>(sampleIndex_) * TimeStep;
	const Vec3 posEci = rotate_z_(localMovedPosition, theta);

	write_pos_(posEci.x, posEci.y, posEci.z);

	++sampleIndex_;
	return true;
}